version: "3.5"

services:
  donkey-cuda:
    container_name: "donkey-cuda"
    build:
      context: .
    ports:
      - "8888:8888"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
